on:
  pull_request:
  merge_group:

name: ci

jobs:
  ci:
    uses: BristolMyersSquibb/blockr.ci/.github/workflows/ci.yaml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      BLOCKR_PAT: ${{ secrets.BLOCKR_PAT }}

  revdep:
    uses: BristolMyersSquibb/blockr.ci/.github/workflows/revdep.yaml@main
    with:
      revdep-packages: |
        BristolMyersSquibb/blockr.dm
    secrets:
      BLOCKR_PAT: ${{ secrets.BLOCKR_PAT }}
