on:
  push:
    branches: main

name: pkgdown

jobs:
  pkgdown:
    uses: BristolMyersSquibb/blockr.ci/.github/workflows/pkgdown.yaml@main
    secrets:
      BLOCKR_PAT: ${{ secrets.BLOCKR_PAT }}
    permissions:
      contents: write
